djangocms_blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf.urls import url

from .feeds import FBInstantArticles, LatestEntriesFeed, TagFeed
from .settings import get_setting
from .views import (
    AuthorEntriesView, CategoryEntriesView, PostArchiveView, PostDetailView, PostListView,
    TaggedListView,
)


def get_urls():
    urls = get_setting('PERMALINK_URLS')
    details = []
    for urlconf in urls.values():
        details.append(
            url(urlconf, PostDetailView.as_view(), name='post-detail'),
        )
    return details


detail_urls = get_urls()

# module-level app_name attribute as per django 1.9+
app_name = 'djangocms_blog'
urlpatterns = [
    url(r'^$',
        PostListView.as_view(), name='posts-latest'),
    url(r'^feed/$',
        LatestEntriesFeed(), name='posts-latest-feed'),
    url(r'^feed/fb/$',
        FBInstantArticles(), name='posts-latest-feed-fb'),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveView.as_view(), name='posts-archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        PostArchiveView.as_view(), name='posts-archive'),
    url(r'^author/(?P<username>[\w\.@+-]+)/$',
        AuthorEntriesView.as_view(), name='posts-author'),
    url(r'^category/(?P<category>[\w\.@+-]+)/$',
        CategoryEntriesView.as_view(), name='posts-category'),
    url(r'^tag/(?P<tag>[-\w]+)/$',
        TaggedListView.as_view(), name='posts-tagged'),
    url(r'^tag/(?P<tag>[-\w]+)/feed/$',
        TagFeed(), name='posts-tagged-feed'),
] + detail_urls

djangocms_blog/templates/djangocms_blog/includes/blog_item.html
{% load djangocms_blog i18n easy_thumbnails_tags cms_tags %}

<article id="post-{{ post.slug }}" class="post-item">
    <header>
        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
        {% if post.subtitle %}
            <h4>{{ post.subtitle }}</h4>
        {% endif %}
        {% block blog_meta %}
            {% include "djangocms_blog/includes/blog_meta.html" %}
        {% endblock %}
    </header>
    {% if image and post.main_image %}
    <div class="blog-visual">
        {% thumbnail post.main_image post.thumbnail_options.size crop=post.thumbnail_options.crop upscale=post.thumbnail_options.upscale subject_location=post.main_image.subject_location as thumb %}
        <img src="{{ thumb.url }}" alt="{{ post.main_image.default_alt_text }}" width="{{ thumb.width }}" height="{{ thumb.height }}" />
    </div>
    {% else %}
        {% media_images post as previews %}
        <div class="blog-visual">
          {% for preview in previews %}<img src="{{ preview }}" />{% endfor %}
        </div>
    {% endif %}
    <div class="blog-lead">
        {% if not TRUNCWORDS_COUNT %}
            {% render_model post "abstract" "" "" "safe" %}
        {% else %}
            {% render_model post "abstract" "" "" "truncatewords_html:TRUNCWORDS_COUNT|safe"  %}
        {% endif %}
    </div>
    <footer class="read-more">
        <a href="{{ post.get_absolute_url }}">{% trans "read more" %} &raquo;</a>
    </footer>
</article>

djangocms_blog/templates/djangocms_blog/includes/blog_meta.html
{% load i18n easy_thumbnails_tags cms_tags %}

<ul class="post-detail">
    {% if post.author %}
    <li>
        {% trans "by" %} <a href="{% url 'djangocms_blog:posts-author' post.author.get_username %}">{% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}</a>
    </li>
    {% endif %}
    <li>
        {{ post.date_published|date:"DATE_FORMAT" }}
    </li>
    {% if post.date_featured %}
    <li>
        {{ post.date_featured|date:"DATE_FORMAT" }}
    </li>
    {% endif %}
</ul>
<ul class="post-detail tags">
    {% if post.categories.exists %}
        {% for category in post.categories.all %}
            {% if category.slug %}
                <li class="category_{{ forloop.counter }}"><a href="{% url 'djangocms_blog:posts-category' category=category.slug %}" class="blog-categories-{{ category.count }}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}</li>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if post.tags.exists %}
        {% for tag in post.tags.all %}
            <li class="tag_{{ forloop.counter }}"><a href="{% url 'djangocms_blog:posts-tagged' tag=tag.slug %}" class="blog-tag blog-tag-{{ tag.count }}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}</li>
        {% endfor %}
    {% endif %}
</ul>