djangocms_blog/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from django.conf.urls import url

from .feeds import FBInstantArticles, LatestEntriesFeed, TagFeed
from .settings import get_setting
from .views import (
    AuthorEntriesView, CategoryEntriesView, PostArchiveView, PostDetailView, PostListView,
    TaggedListView,
)


def get_urls():
    urls = get_setting('PERMALINK_URLS')
    details = []
    for urlconf in urls.values():
        details.append(
            url(urlconf, PostDetailView.as_view(), name='post-detail'),
        )
    return details


detail_urls = get_urls()

# module-level app_name attribute as per django 1.9+
app_name = 'djangocms_blog'
urlpatterns = [
    url(r'^$',
        PostListView.as_view(), name='posts-latest'),
    url(r'^feed/$',
        LatestEntriesFeed(), name='posts-latest-feed'),
    url(r'^feed/fb/$',
        FBInstantArticles(), name='posts-latest-feed-fb'),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveView.as_view(), name='posts-archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        PostArchiveView.as_view(), name='posts-archive'),
    url(r'^author/(?P<username>[\w\.@+-]+)/$',
        AuthorEntriesView.as_view(), name='posts-author'),
    url(r'^category/(?P<category>[\w\.@+-]+)/$',
        CategoryEntriesView.as_view(), name='posts-category'),
    url(r'^tag/(?P<tag>[-\w]+)/$',
        TaggedListView.as_view(), name='posts-tagged'),
    url(r'^tag/(?P<tag>[-\w]+)/feed/$',
        TagFeed(), name='posts-tagged-feed'),
] + detail_urls

djangocms_blog/templates/djangocms_blog/plugins/archive.html
{% load i18n %}{% spaceless %}
<div class="plugin plugin-blog">
    <h3>{% trans "Archive" %}</h3>
    {% regroup dates by date.year as years %}
    {% with current_year=year current_month=month %}
    <ul class="blog-archive">
        {% for year in years %}
        <li{% if year.grouper == current_year %} class="active"{% endif %}>
            <a href="{% url 'djangocms_blog:posts-archive' year=year.grouper %}">{{ year.grouper }}</a>
            <ul>
                {% for month in year.list %}
                <li{% if year.grouper == current_year and month.date.month == current_month %} class="active"{% else %} class="month"{% endif %}>
                    <a href="{% url 'djangocms_blog:posts-archive' year=year.grouper month=month.date|date:"n" %}">
                        {{ month.date|date:"F" }}
                        <span>(
                            {% if month.count > 0 %}
                            {% blocktrans count articles=month.count %}1 article{% plural %}{{ articles }} articles{% endblocktrans %}
                            {% else %}{% trans "0 articles" %}{% endif %}
                        )</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </li>
        {% empty %}
        <li class="blog-empty"><p>{% trans "No article found." %}</p></li>
        {% endfor %}
    </ul>
    {% endwith %}
</div>
{% endspaceless %}

djangocms_blog/templates/djangocms_blog/plugins/authors.html
{% load i18n easy_thumbnails_tags %}{% spaceless %}
<div class="plugin plugin-blog">
    <h3>{% trans "Authors" %}</h3>
    <ul class="blog-authors">
        {% for author in authors_list %}
        <li><a href="{% url 'djangocms_blog:posts-author' author.get_username %}">
            {{ author.get_full_name }}
            <span>(
                {% if author.count > 0 %}
                {% blocktrans count articles=author.count %}1 article{% plural %}{{ articles }} articles{% endblocktrans %}
                {% else %}{% trans "0 articles" %}{% endif %}
            )</span>
        </a></li>
        {% empty %}
        <li class="blog-empty"><p>{% trans "No article found." %}</p></li>
        {% endfor %}
    </ul>
</div>
{% endspaceless %}

djangocms_blog/templates/djangocms_blog/plugins/categories.html
{% load i18n %}{% spaceless %}
<div class="plugin plugin-blog">
    <h3>{% trans "Categories" %}</h3>
    <ul class="blog-categories">
        {% for category in categories %}
            <li><a href="{{ category.get_absolute_url }}" class="blog-categories-{{ category.count }}">
                {{ category.name }}
                <span>(
                    {% if category.count > 0 %}
                    {% blocktrans count articles=category.count %}1 article{% plural %}{{ articles }} articles{% endblocktrans %}
                    {% else %}{% trans "0 articles" %}{% endif %}
                )</span>
            </a></li>
        {% empty %}
            <li class="blog-empty"><p>{% trans "No categories found." %}</p></li>
        {% endfor %}
    </ul>
</div>
{% endspaceless %}

djangocms_blog/templates/djangocms_blog/plugins/latest_entries.html
{% load i18n %}{% spaceless %}
<div class="plugin plugin-blog">
    <div class="blog-latest-entries">
    {% for post in posts_list %}
        {% include "djangocms_blog/includes/blog_item.html" with post=post image="true" TRUNCWORDS_COUNT=TRUNCWORDS_COUNT %}
    {% empty %}
    <p class="blog-empty">{% trans "No article found." %}</p>
    {% endfor %}
    </div>
</div>
{% endspaceless %}

djangocms_blog/templates/djangocms_blog/plugins/tags.html
{% load i18n %}{% spaceless %}
<div class="plugin plugin-blog">
    <h3>{% trans "Tags" %}</h3>
    <ul class="blog-tags">
        {% for tag in tags %}
            <li><a href="{% url 'djangocms_blog:posts-tagged' tag=tag.slug %}" class="blog-tag-{{ tag.count }}">
                {{ tag.name }}
                <span>(
                    {% if tag.count > 0 %}
                    {% blocktrans count articles=tag.count %}1 article{% plural %}{{ articles }} articles{% endblocktrans %}
                    {% else %}{% trans "0 articles" %}{% endif %}
                )</span>
            </a></li>
        {% empty %}
        <li class="blog-empty"><p>{% trans "No article found." %}</p></li>
        {% endfor %}
    </ul>
</div>
{% endspaceless %}